# Generated by Django 6.0.4 on 2026-04-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('items', models.TextField()),
                ('total', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(default='Order Placed', max_length=50)),
            ],
        ),
    ]
