# Generated by Django 6.0.4 on 2026-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField(default='Fresh farm product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
