# Generated by Django 6.0.4 on 2026-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(default='Order Placed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
